// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SCENEGRAPH_WILDFIRE_H_
#define FLATBUFFERS_GENERATED_SCENEGRAPH_WILDFIRE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace wildfire {

struct Vec3;
struct Vec3Builder;

struct VertexBuffer;
struct VertexBufferBuilder;

struct SceneGraph;
struct SceneGraphBuilder;

struct Vec3 FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Vec3Builder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float z() const {
    return GetField<float>(VT_Z, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<float>(verifier, VT_Z, 4) &&
           verifier.EndTable();
  }
};

struct Vec3Builder {
  typedef Vec3 Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(Vec3::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(Vec3::VT_Y, y, 0.0f);
  }
  void add_z(float z) {
    fbb_.AddElement<float>(Vec3::VT_Z, z, 0.0f);
  }
  explicit Vec3Builder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vec3> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vec3>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vec3> CreateVec3(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    float z = 0.0f) {
  Vec3Builder builder_(_fbb);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

struct VertexBuffer FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VertexBufferBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERTEX_COUNT = 4,
    VT_POSITIONS = 6
  };
  uint32_t vertex_count() const {
    return GetField<uint32_t>(VT_VERTEX_COUNT, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<wildfire::Vec3>> *positions() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<wildfire::Vec3>> *>(VT_POSITIONS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_VERTEX_COUNT, 4) &&
           VerifyOffset(verifier, VT_POSITIONS) &&
           verifier.VerifyVector(positions()) &&
           verifier.VerifyVectorOfTables(positions()) &&
           verifier.EndTable();
  }
};

struct VertexBufferBuilder {
  typedef VertexBuffer Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_vertex_count(uint32_t vertex_count) {
    fbb_.AddElement<uint32_t>(VertexBuffer::VT_VERTEX_COUNT, vertex_count, 0);
  }
  void add_positions(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<wildfire::Vec3>>> positions) {
    fbb_.AddOffset(VertexBuffer::VT_POSITIONS, positions);
  }
  explicit VertexBufferBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<VertexBuffer> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<VertexBuffer>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<VertexBuffer> CreateVertexBuffer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t vertex_count = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<wildfire::Vec3>>> positions = 0) {
  VertexBufferBuilder builder_(_fbb);
  builder_.add_positions(positions);
  builder_.add_vertex_count(vertex_count);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<VertexBuffer> CreateVertexBufferDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t vertex_count = 0,
    const std::vector<::flatbuffers::Offset<wildfire::Vec3>> *positions = nullptr) {
  auto positions__ = positions ? _fbb.CreateVector<::flatbuffers::Offset<wildfire::Vec3>>(*positions) : 0;
  return wildfire::CreateVertexBuffer(
      _fbb,
      vertex_count,
      positions__);
}

struct SceneGraph FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SceneGraphBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERTICES = 4
  };
  const wildfire::VertexBuffer *vertices() const {
    return GetPointer<const wildfire::VertexBuffer *>(VT_VERTICES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VERTICES) &&
           verifier.VerifyTable(vertices()) &&
           verifier.EndTable();
  }
};

struct SceneGraphBuilder {
  typedef SceneGraph Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_vertices(::flatbuffers::Offset<wildfire::VertexBuffer> vertices) {
    fbb_.AddOffset(SceneGraph::VT_VERTICES, vertices);
  }
  explicit SceneGraphBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SceneGraph> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SceneGraph>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SceneGraph> CreateSceneGraph(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<wildfire::VertexBuffer> vertices = 0) {
  SceneGraphBuilder builder_(_fbb);
  builder_.add_vertices(vertices);
  return builder_.Finish();
}

inline const wildfire::SceneGraph *GetSceneGraph(const void *buf) {
  return ::flatbuffers::GetRoot<wildfire::SceneGraph>(buf);
}

inline const wildfire::SceneGraph *GetSizePrefixedSceneGraph(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<wildfire::SceneGraph>(buf);
}

template <bool B = false>
inline bool VerifySceneGraphBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<wildfire::SceneGraph>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedSceneGraphBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<wildfire::SceneGraph>(nullptr);
}

inline void FinishSceneGraphBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<wildfire::SceneGraph> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSceneGraphBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<wildfire::SceneGraph> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace wildfire

#endif  // FLATBUFFERS_GENERATED_SCENEGRAPH_WILDFIRE_H_
